### ISSUE TITLE
Can't use RM Mini 3 (5f36) with HOOBS

### ISSUE THREAD

**Issue by fizulnizam** [lprhodes/homebridge-broadlink-rm#598]
So I am using the rm tv fork and I got this in the log:
`Please raise an issue in the GitHub repository (https://github.com/lprhodes/homebridge-broadlink-rm/issues) with details of the type of device and its device type code: "5f36". The device is connected to your network with the IP address "192.168.1.109".`  
and 
`Cannot find module '/home/hoobs/.hoobs/node_modules/homebridge-platform-helper/node_modules/semver/index.js'. Please verify that the package.json has a valid "main" entry
Unable to determine plugin type for "homebridge-broadlink-rm-tv"`

**Comment by fizulnizam** [comment]
#600
