### ISSUE TITLE
upgraded to V3.6.22, garage door icon changed to a Heater control

### ISSUE THREAD

**Issue by trftrftrf** [lprhodes/homebridge-broadlink-rm#583]
hi all, after i upgraded to v3.6.22, i have 2 issues.

1. Error: Cannot find module 'hap-nodejs' 
which i have followed #540 to add a symbolic link.

2. my garage door control icon changed to a Heater temperature control.
i couldn't find any related posts or issues.
i have to force downgrade back to 3.5.5 for my garage door to work.
npm install -g --unsafe-perm homebridge-broadlink-rm@3.5.5

any help on issue 2?

thanks
trf

**Comment by cilianospina** [comment]
no solution, same problem with fan.
I install 3.6.18 and work fine.

**Comment by ronzelver** [comment]
Same here, my Fan shows now as Heater Control and I can't control it with the Home app.
