### ISSUE TITLE
After upgrade to 3.6.13 from 3.6.11: very much [Broadlink] Broadlink RM device at xxx has been re-discovered.

### ISSUE THREAD

**Issue by marcoschmidt79** [lprhodes/homebridge-broadlink-rm#527]
After upgrade to 3.6.13: 

Jan 03 01:26:23 homebridge homebridge[32561]: [3.1.2020, 01:26:23] [Broadlink] Broadlink RM device at xxx is no longer reachable.
Jan 03 01:26:23 homebridge homebridge[32561]: [3.1.2020, 01:26:23] [Broadlink] Broadlink RM device at xxx is no longer reachable.
Jan 03 01:26:23 homebridge homebridge[32561]: [3.1.2020, 01:26:23] [Broadlink] Broadlink RM device at xxx is no longer reachable.
Jan 03 01:26:24 homebridge homebridge[32561]: [3.1.2020, 01:26:24] [Broadlink] Broadlink RM device at xxx has been re-discovered.
Jan 03 01:26:24 homebridge homebridge[32561]: [3.1.2020, 01:26:24] [Broadlink] Broadlink RM device at xxx has been re-discovered.
Jan 03 01:26:24 homebridge homebridge[32561]: [3.1.2020, 01:26:24] [Broadlink] Broadlink RM device at xxx has been re-discovered.

and more

**Comment by pax0707** [comment]
```
[1/3/2020, 1:31:28 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) is no longer reachable.
[1/3/2020, 1:31:29 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) has been re-discovered.
[1/3/2020, 1:31:33 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) is no longer reachable.
[1/3/2020, 1:31:34 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) has been re-discovered.
[1/3/2020, 1:31:38 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) is no longer reachable.
[1/3/2020, 1:31:39 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) has been re-discovered.
[1/3/2020, 1:31:43 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) is no longer reachable.
[1/3/2020, 1:31:44 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) has been re-discovered.
[1/3/2020, 1:31:48 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) is no longer reachable.
[1/3/2020, 1:31:49 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) has been re-discovered.
[1/3/2020, 1:31:53 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) is no longer reachable.
[1/3/2020, 1:31:54 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) has been re-discovered.
[1/3/2020, 1:31:58 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) is no longer reachable.
[1/3/2020, 1:31:59 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) has been re-discovered.
[1/3/2020, 1:32:03 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) is no longer reachable.
[1/3/2020, 1:32:04 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) has been re-discovered.
[1/3/2020, 1:32:08 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) is no longer reachable.
[1/3/2020, 1:32:09 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) has been re-discovered.
[1/3/2020, 1:32:13 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) is no longer reachable.
[1/3/2020, 1:32:14 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) has been re-discovered.
[1/3/2020, 1:32:18 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) is no longer reachable.
[1/3/2020, 1:32:19 AM] [Broadlink RM] Broadlink RM device at 172.16.1.35 (34:ea:34:51:2d:26) has been re-discovered.

**Comment by lprhodes** [comment]
I've release 3.6.14 with a potential fix and extra logging if that doesn't fix it so please paste new logs if you're still seeing the issue.

**Comment by marcoschmidt79** [comment]
The fix doesnt work.

Jan 03 02:21:24 homebridge homebridge[21104]: [3.1.2020, 02:21:24] [Broadlink] Broadlink RM device at 192.168.5.217 (0d:43:b4:aa:9d:58) is no longer reachable. (192.168.5.217, Request timed out)
Jan 03 02:21:25 homebridge homebridge[21104]: [3.1.2020, 02:21:25] [Broadlink] Broadlink RM device at 192.168.5.218 (0d:43:b4:aa:79:70) is no longer reachable. (192.168.5.218, Request timed out)
Jan 03 02:21:26 homebridge homebridge[21104]: [3.1.2020, 02:21:26] [Broadlink] Broadlink RM device at 192.168.5.217 (0d:43:b4:aa:9d:58) has been re-discovered.
Jan 03 02:21:26 homebridge homebridge[21104]: [3.1.2020, 02:21:26] [Broadlink] Broadlink RM device at 192.168.5.216 (0d:43:b4:a1:20:b9) has been re-discovered.
Jan 03 02:21:27 homebridge homebridge[21104]: [3.1.2020, 02:21:27] [Broadlink] Broadlink RM device at 192.168.5.218 (0d:43:b4:aa:79:70) has been re-discovered.
Jan 03 02:21:29 homebridge homebridge[21104]: [3.1.2020, 02:21:29] [Broadlink] Broadlink RM device at 192.168.5.217 (0d:43:b4:aa:9d:58) is no longer reachable. (192.168.5.217, Request timed out)
Jan 03 02:21:31 homebridge homebridge[21104]: [3.1.2020, 02:21:31] [Broadlink] Broadlink RM device at 192.168.5.217 (0d:43:b4:aa:9d:58) has been re-discovered.
Jan 03 02:21:34 homebridge homebridge[21104]: [3.1.2020, 02:21:34] [Broadlink] Broadlink RM device at 192.168.5.216 (0d:43:b4:a1:20:b9) is no longer reachable. (192.168.5.216, Request timed out)
Jan 03 02:21:35 homebridge homebridge[21104]: [3.1.2020, 02:21:35] [Broadlink] Broadlink RM device at 192.168.5.218 (0d:43:b4:aa:79:70) is no longer reachable. (192.168.5.218, Request timed out)
Jan 03 02:21:36 homebridge homebridge[21104]: [3.1.2020, 02:21:36] [Broadlink] Broadlink RM device at 192.168.5.216 (0d:43:b4:a1:20:b9) has been re-discovered.
Jan 03 02:21:37 homebridge homebridge[21104]: [3.1.2020, 02:21:37] [Broadlink] Broadlink RM device at 192.168.5.218 (0d:43:b4:aa:79:70) has been re-discovered.
Jan 03 02:21:39 homebridge homebridge[21104]: [3.1.2020, 02:21:39] [Broadlink] Broadlink RM device at 192.168.5.217 (0d:43:b4:aa:9d:58) is no longer reachable. (192.168.5.217, Request timed out)
Jan 03 02:21:41 homebridge homebridge[21104]: [3.1.2020, 02:21:41] [Broadlink] Broadlink RM device at 192.168.5.217 (0d:43:b4:aa:9d:58) has been re-discovered.
Jan 03 02:21:44 homebridge homebridge[21104]: [3.1.2020, 02:21:44] [Broadlink] Broadlink RM device at 192.168.5.217 (0d:43:b4:aa:9d:58) is no longer reachable. (192.168.5.217, Request timed out)
Jan 03 02:21:44 homebridge homebridge[21104]: [3.1.2020, 02:21:44] [Broadlink] Broadlink RM device at 192.168.5.216 (0d:43:b4:a1:20:b9) is no longer reachable. (192.168.5.216, Request timed out)
Jan 03 02:21:45 homebridge homebridge[21104]: [3.1.2020, 02:21:45] [Broadlink] Broadlink RM device at 192.168.5.218 (0d:43:b4:aa:79:70) is no longer reachable. (192.168.5.218, Request timed out)
Jan 03 02:21:46 homebridge homebridge[21104]: [3.1.2020, 02:21:46] [Broadlink] Broadlink RM device at 192.168.5.216 (0d:43:b4:a1:20:b9) has been re-discovered.
Jan 03 02:21:46 homebridge homebridge[21104]: [3.1.2020, 02:21:46] [Broadlink] Broadlink RM device at 192.168.5.217 (0d:43:b4:aa:9d:58) has been re-discovered.
Jan 03 02:21:47 homebridge homebridge[21104]: [3.1.2020, 02:21:47] [Broadlink] Broadlink RM device at 192.168.5.218 (0d:43:b4:aa:79:70) has been re-discovered.
Jan 03 02:21:49 homebridge homebridge[21104]: [3.1.2020, 02:21:49] [Broadlink] Broadlink RM device at 192.168.5.216 (0d:43:b4:a1:20:b9) is no longer reachable. (192.168.5.216, Request timed out)
Jan 03 02:21:51 homebridge homebridge[21104]: [3.1.2020, 02:21:51] [Broadlink] Broadlink RM device at 192.168.5.216 (0d:43:b4:a1:20:b9) has been re-discovered.
Jan 03 02:21:55 homebridge homebridge[21104]: [3.1.2020, 02:21:55] [Broadlink] Broadlink RM device at 192.168.5.218 (0d:43:b4:aa:79:70) is no longer reachable. (192.168.5.218, Request timed out)
Jan 03 02:21:57 homebridge homebridge[21104]: [3.1.2020, 02:21:57] [Broadlink] Broadlink RM device at 192.168.5.218 (0d:43:b4:aa:79:70) has been re-discovered.
Jan 03 02:21:59 homebridge homebridge[21104]: [3.1.2020, 02:21:59] [Broadlink] Broadlink RM device at 192.168.5.217 (0d:43:b4:aa:9d:58) is no longer reachable. (192.168.5.217, Request timed out)
Jan 03 02:21:59 homebridge homebridge[21104]: [3.1.2020, 02:21:59] [Broadlink] Broadlink RM device at 192.168.5.216 (0d:43:b4:a1:20:b9) is no longer reachable. (192.168.5.216, Request timed out)
Jan 03 02:22:01 homebridge homebridge[21104]: [3.1.2020, 02:22:01] [Broadlink] Broadlink RM device at 192.168.5.217 (0d:43:b4:aa:9d:58) has been re-discovered.
Jan 03 02:22:01 homebridge homebridge[21104]: [3.1.2020, 02:22:01] [Broadlink] Broadlink RM device at 192.168.5.216 (0d:43:b4:a1:20:b9) has been re-discovered.

**Comment by lprhodes** [comment]
Can you try editing the helpers/getDevice.js file on line 12 and change the timeout to 5000 and restart homebridge and report back please?

**Comment by lprhodes** [comment]
I've release 3.6.15 with some performance tweaks, it could have an impact if you had multiple RM devices but it looks like only one of you do.

**Comment by larryemi** [comment]
after updated 3.6.15 from 3.6.11(had issue too can't run) and now still not working

[1/3/2020, 10:05:57 AM] TypeError: log is not a function
    at setupPing (/homebridge/node_modules/homebridge-broadlink-rm/helpers/getDevice.js:20:7)
    at startPing (/homebridge/node_modules/homebridge-broadlink-rm/helpers/getDevice.js:28:3)
    at Broadlink.<anonymous> (/homebridge/node_modules/homebridge-broadlink-rm/helpers/getDevice.js:77:5)
    at Broadlink.emit (events.js:210:5)
    at Device.<anonymous> (/homebridge/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs-rm/index.js:226:12)
    at Device.emit (events.js:210:5)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs-rm/index.js:290:14)
    at Socket.emit (events.js:210:5)
    at UDP.onMessage (dgram.js:861:8)

**Comment by cilianospina** [comment]
> after updated 3.6.15 from 3.6.11(had issue too can't run) and now still not working
> 
> [1/3/2020, 10:05:57 AM] TypeError: log is not a function
> at setupPing (/homebridge/node_modules/homebridge-broadlink-rm/helpers/getDevice.js:20:7)
> at startPing (/homebridge/node_modules/homebridge-broadlink-rm/helpers/getDevice.js:28:3)
> at Broadlink. (/homebridge/node_modules/homebridge-broadlink-rm/helpers/getDevice.js:77:5)
> at Broadlink.emit (events.js:210:5)
> at Device. (/homebridge/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs-rm/index.js:226:12)
> at Device.emit (events.js:210:5)
> at Socket. (/homebridge/node_modules/homebridge-broadlink-rm/node_modules/broadlinkjs-rm/index.js:290:14)
> at Socket.emit (events.js:210:5)
> at UDP.onMessage (dgram.js:861:8)

Same problem after update 3.6.15, I return to 3.6.13

**Comment by lprhodes** [comment]
3.6.16 is out with a fix for that. Sorry about this, I'm on the road without an RM device to properly test on.

**Comment by larryemi** [comment]
> 3.6.16 is out with a fix for that. Sorry about this, I'm on the road without an RM device to properly test on.

Seem like working fine. Thank you

**Comment by marcoschmidt79** [comment]
ok, perfect, thank you
